add status

diff --git a/.github/workflows/retry-workflow.yml b/.github/workflows/retry-workflow.yml
--- a/.github/workflows/retry-workflow.yml
+++ b/.github/workflows/retry-workflow.yml
@@ -1,3 +1,5 @@
+name: Workflow Finished
+
 on:
   workflow_run:
     workflows:
@@ -5,9 +7,15 @@ on:
     types:
      - completed
 
+permissions:
+  contents: read
+  pull-requests: read
+  actions: write
+
 jobs:
 
-  always:
+  show-context:
+     name: Show Github Context
      runs-on: ubuntu-latest
      steps:
        - name: event
@@ -15,14 +23,26 @@ jobs:
            GITHUB_CONTEXT: ${{ toJson(github) }}
          run: |
            echo "$GITHUB_CONTEXT"
-  on-success:
-    runs-on: ubuntu-latest
-    if: ${{ github.event.workflow_run.conclusion == 'success' }}
-    steps:
-      - run: echo 'The triggering workflow passed'
 
   on-failure:
     runs-on: ubuntu-latest
-    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
+    if: ${{ github.event.workflow_run.conclusion == 'failure' && github.event.workflow_run.run_attempt < 5 }}
     steps:
-      - run: echo 'The triggering workflow failed'
+      - run: |
+          gh run rerun ${{ github.event.workflow_run.id }} --failed
+  
+  # Branch protection rules require this to run with exit code 0.
+  set-pipeline-exit-status:
+    name: Set the ${{ github.event.workflow.name }} Pipeline Exit Status
+    if: ${{ github.event.workflow_run.conclusion == 'success'  || github.event.workflow_run.run_attempt >= 5 }}
+    runs-on: ubuntu-latest
+    needs:
+      - show-context
+      - on-failure
+    steps:
+      - run: 
+          if [ "${{ github.event.workflow_run.conclusion }}" != "success" ]; then
+            exit 1
+          else
+            exit 0
+          fi
